Repository Copenhagen-Squad/MovieApp, pull requests merged in 2025-09, with the labels that each got.

#9 refactor/some-components
  app/src/main/java/com/karrar/movieapp/ui/search/SearchFragment.kt
  app/src/main/res/color/selector_chip_background.xml
  app/src/main/res/color/selector_chip_stroke.xml
  app/src/main/res/color/selector_chip_text.xml
  app/src/main/res/drawable/cast_card.xml
  app/src/main/res/drawable/collection_item.xml
  app/src/main/res/drawable/rating_container.xml
  app/src/main/res/layout/chip_item_category.xml
  app/src/main/res/layout/fragment_exploring.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_actor.xml
  app/src/main/res/layout/item_actor_home.xml
  app/src/main/res/layout/item_actor_search.xml
  app/src/main/res/layout/item_cast.xml
  app/src/main/res/layout/item_list_details.xml
  app/src/main/res/layout/item_media_search.xml
  app/src/main/res/layout/item_saved_list.xml
  app/src/main/res/layout/item_search_history.xml
  app/src/main/res/layout/item_trend.xml
  app/src/main/res/values/themes.xml
Labels: refactor

#18 refactor/profile-screen-ui
  app/src/main/res/drawable/chip.xml
  app/src/main/res/drawable/collection_item.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#23 Refactor History Screen UI
  app/src/main/java/com/karrar/movieapp/ui/profile/watchhistory/WatchHistoryFragment.kt
  app/src/main/res/layout/fragment_watch_history.xml
  app/src/main/res/layout/item_watch_history.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#43 Feature: Add Onboarding Screen
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/karrar/movieapp/ui/main/MainActivity.kt
  app/src/main/java/com/karrar/movieapp/ui/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/karrar/movieapp/ui/onboarding/OnBoardingInteractionListener.kt
  app/src/main/java/com/karrar/movieapp/ui/onboarding/OnBoardingPageTransformer.kt
  app/src/main/java/com/karrar/movieapp/ui/onboarding/OnBoardingPagerAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/onboarding/OnBoardingScreenEvents.kt
  app/src/main/java/com/karrar/movieapp/ui/onboarding/OnBoardingState.kt
  app/src/main/java/com/karrar/movieapp/ui/onboarding/OnBoardingViewModel.kt
  app/src/main/java/com/karrar/movieapp/utilities/StringValue.kt
  app/src/main/res/drawable/ic_left_arrow.xml
  app/src/main/res/drawable/ic_right_arrow.xml
  app/src/main/res/drawable/left_on_boarding_back_btn.xml
  app/src/main/res/drawable/on_boarding_1.png
  app/src/main/res/drawable/on_boarding_2.png
  app/src/main/res/drawable/on_boarding_3.png
  app/src/main/res/drawable/right_on_boarding_forward_btn.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/item_onboarding_page.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#37 refactor/loading-animation
  app/src/main/res/layout/fragment_exploring.xml
  app/src/main/res/layout/fragment_list_details.xml
  app/src/main/res/layout/fragment_movie_details.xml
  app/src/main/res/layout/fragment_my_lists.xml
  app/src/main/res/layout/fragment_my_ratings.xml
  app/src/main/res/layout/fragment_review.xml
Labels: refactor

#47 refactor/nav-bar-ui
  app/src/main/java/com/karrar/movieapp/ui/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: refactor

#48 component/rating-stars
  app/src/main/java/com/karrar/movieapp/ui/components/ratingBar/StarRatingView.kt
  app/src/main/res/layout/rating_stars.xml
  app/src/main/res/layout/your_rating.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#55 Add GitHub Actions workflow for Firebase release automation
  .github/workflows/android-ci.yml
  .github/workflows/app-release.yml
  app/build.gradle
  version.properties
Labels: feature

#54 refactor screen app bar
  app/src/main/java/com/karrar/movieapp/ui/components/header/AppBar.kt
  app/src/main/java/com/karrar/movieapp/ui/myList/CreatedCollectionAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/myList/MyCollectionFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/myList/MyCollectionViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/myList/collectionDetails/CollectionDetailsFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/myList/collectionDetails/CollectionDetailsViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/myList/collectionDetails/collectionDetailsAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/myList/collectionDetails/collectionDetailsUIState/CollectionDetailsUIEvent.kt
  app/src/main/java/com/karrar/movieapp/ui/myList/myCollectionUIState/MyCollectionUIEvent.kt
  app/src/main/java/com/karrar/movieapp/ui/profile/ProfileFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/profile/watchhistory/WatchHistoryAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/profile/watchhistory/WatchHistoryFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/profile/watchhistory/WatchHistoryUIEvent.kt
  app/src/main/java/com/karrar/movieapp/ui/profile/watchhistory/WatchHistoryViewModel.kt
  app/src/main/java/com/karrar/movieapp/utilities/BindingAdapter.kt
  app/src/main/res/drawable/ic_add_outline.xml
  app/src/main/res/layout/appbar.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_list_details.xml
  app/src/main/res/layout/fragment_my_lists.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_season.xml
  app/src/main/res/layout/fragment_watch_history.xml
  app/src/main/res/layout/your_rating.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  version.properties
Labels: refactor

#59 refactor/no-items-state
  .github/workflows/app-release.yml
  app/src/main/res/drawable/circle_shape_no_items.xml
  app/src/main/res/layout/fragment_list_details.xml
  app/src/main/res/layout/fragment_my_ratings.xml
  app/src/main/res/layout/fragment_watch_history.xml
  app/src/main/res/layout/no_collection.xml
  app/src/main/res/layout/no_history.xml
  app/src/main/res/layout/no_ratings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
  version.properties
Labels: refactor

#62 Feature/match screen
  app/build.gradle
  app/src/main/java/com/karrar/movieapp/data/MatchMapper.kt
  app/src/main/java/com/karrar/movieapp/data/MatchResultsAdapter.kt
  app/src/main/java/com/karrar/movieapp/data/remote/service/MovieService.kt
  app/src/main/java/com/karrar/movieapp/data/repository/MovieRepository.kt
  app/src/main/java/com/karrar/movieapp/data/repository/MovieRepositoryImp.kt
  app/src/main/java/com/karrar/movieapp/di/NetworkModule.kt
  app/src/main/java/com/karrar/movieapp/di/RepositoryModule.kt
  app/src/main/java/com/karrar/movieapp/domain/MatchEvent.kt
  app/src/main/java/com/karrar/movieapp/domain/QuestionType.kt
  app/src/main/java/com/karrar/movieapp/domain/usecases/GetMatchRecommendationsUseCase.kt
  app/src/main/java/com/karrar/movieapp/ui/home/HomeFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/main/MainActivity.kt
  app/src/main/java/com/karrar/movieapp/ui/mappers/MatchUiState.kt
  app/src/main/java/com/karrar/movieapp/ui/match/BindingAdapters.kt
  app/src/main/java/com/karrar/movieapp/ui/match/DurationUiState.kt
  app/src/main/java/com/karrar/movieapp/ui/match/MatchItemUI.kt
  app/src/main/java/com/karrar/movieapp/ui/match/MatchPages.kt
  app/src/main/java/com/karrar/movieapp/ui/match/MatchPostersAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/match/MatchResultsFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/match/MatchResultsViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/match/MatchScreenFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/match/MatchScreenViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/match/MovieScreenState.kt
  app/src/main/java/com/karrar/movieapp/ui/match/ReviewUiState.kt
  app/src/main/java/com/karrar/movieapp/ui/match/SuggestItemUiState.kt
  app/src/main/java/com/karrar/movieapp/ui/match/ViewMode.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/Choice.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/MatchQuestionsFragment.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/MatchQuestionsViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/Question.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/QuestionInteractionListener.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/QuestionUiState.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/adapter/ChoicesAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/match/questions/adapter/QuestionAdapter.kt
  app/src/main/java/com/karrar/movieapp/ui/movieDetails/DetailIntractionListener.kt
  app/src/main/java/com/karrar/movieapp/ui/movieDetails/mapper/MovieDetailsUIStateMapper.kt
  app/src/main/java/com/karrar/movieapp/utilities/BindingAdapter.kt
  app/src/main/java/com/karrar/movieapp/utilities/Constants.kt
  app/src/main/res/drawable/bg_circle_tertiary.xml
  app/src/main/res/drawable/button_secondry_bg.xml
  app/src/main/res/drawable/circular_progress.xml
  app/src/main/res/drawable/ic_bookmark_filled.xml
  app/src/main/res/drawable/ic_magic_stick_colored.xml
  app/src/main/res/drawable/ic_progress.xml
  app/src/main/res/drawable/mood_btn.xml
  app/src/main/res/layout/fragment_match_questions.xml
  app/src/main/res/layout/fragment_match_result.xml
  app/src/main/res/layout/fragment_match_screen.xml
  app/src/main/res/layout/item_genre_question_choice.xml
  app/src/main/res/layout/item_match_poster.xml
  app/src/main/res/layout/item_movie_detail_header.xml
  app/src/main/res/layout/item_question_choice.xml
  app/src/main/res/layout/list_question_choices.xml
  app/src/main/res/navigation/movie_navigation.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature

#69 reafctor/home-screen
  app/src/main/java/com/karrar/movieapp/domain/usecases/home/HomeUseCasesContainer.kt
  app/src/main/java/com/karrar/movieapp/ui/home/HomeViewModel.kt
  app/src/main/java/com/karrar/movieapp/ui/home/homeUiState/HomeUiState.kt
  app/src/main/java/com/karrar/movieapp/utilities/BindingAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  version.properties
Labels: refactor

#70 Refactor login button and loading indicator style
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/values/dimens.xml
  version.properties
Labels: refactor

#72 refactor: improve viewpager styling in match results to prevent crash…
  app/src/main/java/com/karrar/movieapp/ui/match/MatchResultsFragment.kt
  version.properties
Labels: bug-fix

#76 refactor/detailsCard-reviewScreen
  app/src/main/java/com/karrar/movieapp/ui/reviews/ReviewFragment.kt
  app/src/main/res/layout/item_movie_detail_header.xml
  app/src/main/res/layout/item_tv_show_details_header.xml
Labels: refactor
